---
name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Install dependencies
        run: go mod download
      - name: Build binary
        run: make
      - name: Run and make request
        run: |
          ./bin/dotkatapult --port=8080 &
          curl --silent --retry 10 --retry-delay 1 --retry-connrefused \
              http://localhost:8080/
